---
ping: {}

log:
  level: INFO

entryPoints:
  http:
    address: ":80"
    transport:
      respondingTimeouts:
        readTimeout: 60
  https:
    address: ":443"
    transport:
      respondingTimeouts:
        readTimeout: 60

certificatesResolvers:
  letsencrypt:
    acme:
      storage: /acme/acme.json
      httpChallenge:
        entryPoint: http

providers:
  # load our main traefik conf which has dynamic content
  # see https://doc.traefik.io/traefik/reference/install-configuration/providers/others/file/
  file:
    directory: /etc/traefik/dynamic
  docker:
    network: default
    exposedByDefault: false
