name: Update from Islandora Starter Site

on:
  schedule:
    - cron: '0 7 * * *' # Runs daily at 7am UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Update from starter site
        run: make overwrite-starter-site

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make create-starter-site-pr
